service: api-tpe-digital

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline-sqs
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage}
  profile: tpe
  timeout: 30
  memorySize: 128
  apiGateway:
    # accepted binary type for file uploads
    binaryMediaTypes:
      - 'multipart/form-data'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:ListBucket"
      Resource: "*"

custom:
  dotenv:
    path: .env
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    keepNames: true
    target: 'node20'
    define:
      'require.resolve': undefined
    platform: 'node'
    concurrency: 10
  serverless-offline:
    allowCache: true
    noPrependStageInUrl: true
    noTimeout: true
    reloadHandler: true
    endpoint: http://0.0.0.0:9324
  serverless-offline-sqs:
      autoCreate: true
      apiVersion: '2012-11-05'
      endpoint: http://0.0.0.0:9324

functions: 
  - ${file(./resources/infra.yml)}
  - ${file(./resources/auth.yml)}
  - ${file(./resources/groups.yml)}
  - ${file(./resources/designations.yml)}
  - ${file(./resources/participants.yml)}

resources:
  Resources:
    DesignationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: DesignationQueue.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
        VisibilityTimeout: 60 # serve para garantir que a mensagem não será processada por outro lambda antes de ser excluída
    WhatsAppMessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: WhatsAppMessageQueue
        VisibilityTimeout: 300
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt WhatsAppMessageQueueDLQ.Arn
          maxReceiveCount: 5
    WhatsAppMessageQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: WhatsAppMessageQueueDLQ

package:
  individually: true