service: api-tpe-digital

plugins:
  - serverless-prune-plugin
  - serverless-domain-manager
  - serverless-dotenv-plugin
  - serverless-esbuild
	
custom:
  customDomain:
    domainName: api.tpedigital.com.br
    basePath: 'hmg'
    stage: ${opt:stage}
    certificateName: 'tpedigital.com.br'
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false
  esbuild:
      exclude: []
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage}
  timeout: 30
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "sqs:SendMessage"
        - "sqs:ReceiveMessage"
        - "sqs:GetQueueAttributes"
      Resource: 
        - "arn:aws:sqs:us-east-1:533267195262:api-tpe-digital-hmg-designation-queue.fifo"
        - "arn:aws:sqs:us-east-1:533267195262:api-tpe-digital-hmg-whatsapp-message-queue"
        - "arn:aws:sqs:us-east-1:533267195262:api-tpe-digital-hmg-whatsapp-message-queue-dlq"
  environment:
    NODE_ENV: ${self:provider.stage}
    WHATSAPP_MESSAGE_QUEUE: { Ref: WhatsAppMessageQueue }
    WHATSAPP_MESSAGE_DLQ: { Ref: WhatsAppMessageQueueDLQ }


functions: 
  - ${file(./resources/infra.yml)}
  - ${file(./resources/auth.yml)}
  - ${file(./resources/groups.yml)}
  - ${file(./resources/designations.yml)}
  - ${file(./resources/participants.yml)}

resources:
  Resources:
    DesignationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-designation-queue.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
        VisibilityTimeout: 60 # serve para garantir que a mensagem não será processada por outro lambda antes de ser excluída
    WhatsAppMessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-whatsapp-message-queue
        VisibilityTimeout: 300
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt WhatsAppMessageQueueDLQ.Arn
          maxReceiveCount: 5
    WhatsAppMessageQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-whatsapp-message-queue-dlq
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

package:
  individually: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'