export enum ParticipantProfile {
    COORDINATOR = 'COORDINATOR',
    ASSISTANT_COORDINATOR = 'ASSISTANT_COORDINATOR',
    CAPTAIN = 'CAPTAIN',
    ASSISTANT_CAPTAIN = 'ASSISTANT_CAPTAIN',
    PARTICIPANT = 'PARTICIPANT',
    ADMIN_ANALYST = 'ADMIN_ANALYST',
}