include classpath("application.conf")

node-address {
    protocol = http
    host = "*"
    port = 9324
    context-path = ""
}

rest-sqs {
    enabled = true
    bind-port = 9324
    bind-hostname = "0.0.0.0"
    sqs-limits = relaxed
}

queues {
    WhatsAppMessageQueue {
        defaultVisibilityTimeout = 30s
        delay = 0s
        receiveMessageWait = 0s
        deadLettersQueue {
            name = "WhatsAppMessageQueueDLQ"
            maxReceiveCount = 10
        }
    }
    WhatsAppMessageQueueDLQ {
        defaultVisibilityTimeout = 30s
        delay = 0s
        receiveMessageWait = 0s
    }
    DesignationUpdateQueue {
        defaultVisibilityTimeout = 30s
        delay = 0s
        receiveMessageWait = 0s
    }
}
