name: Serverless Framework Deployment - Dev

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Check types
      run: npm run build
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Serverless Framework deploy
      run: npm run deploy:dev
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        Z_API_URL: ${{ secrets.Z_API_URL }}
        INSTANCE_ID: ${{ secrets.INSTANCE_ID }}
        INSTANCE_TOKEN: ${{ secrets.INSTANCE_TOKEN }}
        USER_TOKEN_ID: ${{ secrets.USER_TOKEN_ID }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
